// <auto-generated />
namespace Ajf.RideShare.Migrate
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EventExtend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventExtend));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141651564_EventExtend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
